### ISSUE TITLE
About the add new stock

### ISSUE THREAD

**Issue by wenshen7** [wenshen7/Burzly-Food-Ordering-System#1]
I think the add new stock feature must has a input field is allow users to enter stock quantity right? The input field should use drop down list, combo box, text box or masked text box is better?

**Comment by mhyap999** [comment]
Ya, so can prevent customer to have typo error. We also can add the picture box to let staff upload the product photo.

**Comment by wenshen7** [comment]
Good suggestion, with picture, staff can clearly know what product is that.

**Comment by jazlynyin** [comment]
I think the stock quantity input field can be text box with validation which only allow the users to enter number. This can prevent the users for typing error which have been included some alphabets.

**Comment by wenshen7** [comment]
How about drop down list? Drop down list also can prevent the users for typing error or enter invalid input.

**Comment by Kezin** [comment]
I don't think drop down list is a good suggestion as the stock quantity may be up to 100, it's not possible for users to choose from 100 numbers in drop down list.

**Comment by leonzly** [comment]
I think the better way is use text box to do the stock quantity.

**Comment by Kezin** [comment]
I agree with Yin Yin and Tau Leong, text box with validation is the best input field for quantity.

**Comment by wenshen7** [comment]
All right, thank you for giving the valuable opinion. The input field for the stock quantity will use the text box with validation and a picture box will be included in the add new stock feature.

**Comment by leonzly** [comment]
What do you mean add new stock feature?? can you briefly explain it?

**Comment by wenshen7** [comment]
Sure. The add new stock feature is the feature that allow the system users to entering a new stock such as cheese, hot dog, onion and et cetera into the system's database for future use. Without this feature, the system users is unable to manage the stock of their company.

**Comment by mhyap999** [comment]
We also need a status drop down list option to let staff choose whether the stock is still left in the store or not.

**Comment by mhyap999** [comment]
Thank you for your explanation. Now I clear about it already.

**Comment by wenshen7** [comment]
Ming Han, thank for your suggestion. It is necessary to include a status drop down list to state the stock is available or not.

**Comment by wenshen7** [comment]
You're welcome. I will close this issue since we get a conclusion already. Thanks for all giving your opinion on this issue.

**Comment by wenshen7** [comment]
sdfg
